global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using HanGao.Model;
global using Generic_Extension;
global using KUKA_Val_Attribute_Method;
global using PropertyChanged;
global using System.Windows;
global  using System.Windows.Controls;
global  using System.Windows.Input;
global  using Soceket_KUKA.Models;
global using System.Collections.ObjectModel;
global  using HanGao.Xml_Date.Xml_Models;
global using Nancy.Helpers;
global  using System.ComponentModel;
global using MvCamCtrl.NET;
global using MvCamCtrl.NET.CameraParams;
global using MVS_SDK;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using HalconDotNet;
global using HanGao.Socket_KUKA;
global  using System.Threading;
global using Soceket_Connect;
global using System.Windows.Media;
global using HanGao.Errorinfo;
global using KUKA_Socket.Models;
global using Soceket_KUKA;
global using Halcon_SDK_DLL;
global using Halcon_SDK_DLL.Model;
global using System.IO;
global using HanGao.Xml_Date.Vision_XML.Vision_Model;
global using static HanGao.ViewModel.User_Control_Log_ViewModel;
global using static HanGao.Xml_Date.Vision_XML.Vision_WriteRead.Vision_Xml_Method;
global using static HanGao.ViewModel.Global_Seting_Status;
global using System.Windows.Media.Media3D;

