using PropertyChanged;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using HanGao.View.FrameShow;
using Microsoft.Toolkit.Mvvm.ComponentModel;
using Microsoft.Toolkit.Mvvm.Input;
using Microsoft.Toolkit.Mvvm.Messaging;
using System.Threading.Tasks;
using System.ComponentModel;
using System;
using System.Reflection;
using static HanGao.ViewModel.Messenger_Eunm.Messenger_Name;
using static Soceket_Connect.Socket_Connect;
using HalconDotNet;

namespace HanGao.ViewModel
{
    [AddINotifyPropertyChangedInterface]
    public  class UC_Visal_Function_VM : ObservableRecipient
    {






        /// <summary>
        /// 加载属性水槽类型
        /// </summary>
        public ICommand User_Comm
        {
            get => new RelayCommand<Vision>((Sm) =>
            {
                FrameworkElement e = Sm as FrameworkElement;
                // Local iconic variables 

                HObject ho_Image;
                HTuple hv_WindowHandle = null;


                //HOperatorSet.OpenWindow(0, 0, Sm.Halcon_Window.Width, Sm.Halcon_Window.Height , Sm.Halcon_Window.HalconWindow, "", "", out hv_WindowHandle);
                // HDevWindowStack.Push(hv_WindowHandle);
                //// Initialize local and output iconic variables 
                //HOperatorSet.GenEmptyObj(out ho_Image);
                ////Image Acquisition 01: Code generated by Image Acquisition 01
                //ho_Image.Dispose();
                //HOperatorSet.ReadImage(out ho_Image, "C:/Users/zhiwei2.he/Desktop/微信图片_20220826134820.jpg");

                //if (HDevWindowStack.IsOpen())
                //{
                //    HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());
                //}

                //ho_Image.Dispose();



                // Local iconic variables 

              

                // Local control variables 

                HTuple hv_AcqHandle = new HTuple();
                // Initialize local and output iconic variables 
                HOperatorSet.GenEmptyObj(out ho_Image);
                HOperatorSet.OpenWindow(0, 0, Sm.Halcon_Window.Width, Sm.Halcon_Window.Height, Sm.Halcon_Window.HalconWindow, "", "", out hv_WindowHandle);
                //Image Acquisition 01: Code generated by Image Acquisition 01
                hv_AcqHandle.Dispose();
                HOperatorSet.OpenFramegrabber("GigEVision2", 0, 0, 0, 0, 0, 0, "progressive",
                    -1, "default", "force_ip=10.30.6.192/C4:2F:90:F2:41:96/10.30.6.144/255.255.255.0",
                    "false", "default", "c42f90f24196_Hikvision_MVCA06010GM", 0, -1, out hv_AcqHandle);
                while ((int)(1) != 0)
                {
                    ho_Image.Dispose();
                    HOperatorSet.GrabImage(out ho_Image, hv_AcqHandle);
                    //Image Acquisition 01: Do something
                    HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());


                }
                //HOperatorSet.CloseFramegrabber(hv_AcqHandle);
                //ho_Image.Dispose();

                //hv_AcqHandle.Dispose();




            });
        }

    }
}
